#%RAML 1.0 Library
uses:
  secrets: secrets.raml

types:
  DockerConfig:
    type: object
    properties:
      secret:
        type: secrets.SecretDef
        required: true
    description: |
      Docker config.json. For now it can be specifed only as a secret
      name into a secret store, and the corresponding value should be
      a stringified valid JSON object which can be found in
      `~/.docker/config.json`.
